[build]
  publish = "."

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"
